theme: jekyll-theme-slate
title: ICF UX working Group
description: Our mission is to highlight the emerging application-level problems that must be addressed to ensure high-quality user experiences (UX) and developer experiences (DX) on an IBC connected Internet of Blockchains. We want to help lead discussions about and improve UX/DX standards through a collaborative, open dialogue.
show_downloads: false
